<?php

namespace Database\Seeders\Admin;

use App\Models\Admin\SiteSections;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Constants\SiteSectionConst;
use Illuminate\Support\Str;

class SiteSectionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $site_sections = array(
            array('key' => 'site_cookie','value' => '{"status":true,"link":"https:\\/\\/www.appdevs.net\\/policy","desc":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book."}','status' => '1','serialize' => NULL,'created_at' => '2024-03-18 04:01:35','updated_at' => '2024-03-18 04:01:35'),
            array('key' => 'glance-section','value' => '{"items":{"65f7bc9fb5298":{"image":"","id":"65f7bc9fb5298"},"65f7bc9fb529c":{"image":"","id":"65f7bc9fb529c"},"65f7bc9fb529d":{"image":"","id":"65f7bc9fb529d"},"65f7bc9fb529e":{"image":"","id":"65f7bc9fb529e"},"65f7bc9fb529f":{"image":"","id":"65f7bc9fb529f"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-18 04:01:35','updated_at' => '2024-03-18 04:01:35'),
            array('key' => 'banner-section','value' => '{"image":"seeder/banner.webp","language":{"en":{"title":"NFC Technology","heading":"Providing Payment System In | Single Tap","sub_heading":"NFCPay is a community-led organization of hundreds of organizations looking to reinvent how we connect.","button_name":"Explore Now"},"es":{"title":null,"heading":null,"sub_heading":null,"button_name":null},"ar":{"title":null,"heading":null,"sub_heading":null,"button_name":null}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 05:30:14','updated_at' => '2024-03-25 07:59:53'),
            array('key' => 'about-us-section','value' => '{"language":{"en":{"title":"About us","heading":"The Way of the | Wayfinding Mark","sub_heading":"Checking in on the Wayfinding Mark, and how it\\u2019s being used six months after its release. Former NFC Forum Chair and SONY Executive Honored for Outstanding Leadership and Commitment to NFC Technology\\r\\n\\r\\nWith the holidays fast approaching, it\\u2019s time to start thinking about gift ideas. While the NFC Forum may not be your traditional go-to site for gift ideas, we know a little bit about near-field communication. Connected, battery-powered devices have transformed our existence. Yet a familiar problem remains. As the number of devices has increased, so too have the cables, plug sockets, proprietary adaptors."},"es":{"title":null,"heading":null,"sub_heading":null},"ar":{"title":null,"heading":null,"sub_heading":null}},"image_one":"seeder/about1.webp","image_two":"seeder/about2.webp"}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 05:39:32','updated_at' => '2024-03-27 04:35:59'),
            array('key' => 'services-section','value' => '{"language":{"en":{"title":"Services","heading":"Our Upheld What We | Serve"},"es":{"title":null,"heading":null},"ar":{"title":null,"heading":null}},"items":{"66010e6589c06":{"language":{"en":{"title":"NFC Encoding","description":"Encoding Service for NFC Tags. Please, specify the total number of NFC Tags to be programmed. Add the product to the cart. After completing the order, click here to send the instructions."},"es":{"title":null,"description":null},"ar":{"title":null,"description":null}},"id":"66010e6589c06","icon":"fab fa-codepen"},"66010e837f321":{"language":{"en":{"title":"Monochrome Printing","description":"Optional service in addition to the purchase of NFC Stickers and NFC Cards. We can quickly print on adhesive Tags on Reel and on PVC Cards, in one color."},"es":{"title":null,"description":null},"ar":{"title":null,"description":null}},"id":"66010e837f321","icon":"fas fa-print"},"66010ea1acbe4":{"language":{"en":{"title":"UID Reading","description":"Optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email. After completing the order, click here to submit"},"es":{"title":null,"description":null},"ar":{"title":null,"description":null}},"id":"66010ea1acbe4","icon":"fas fa-book-open"},"66010eb722dc9":{"language":{"en":{"title":"Mobile Payments","description":"Not surprisingly, the most popular use of NFC has turned out to be mobile payments. While most of Europe and Canada were already using physical contactless payment cards"},"es":{"title":null,"description":null},"ar":{"title":null,"description":null}},"id":"66010eb722dc9","icon":"fas fa-mobile"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 05:40:11','updated_at' => '2024-03-27 05:32:56'),
            array('key' => 'testimonial-section','value' => '{"language":{"en":{"heading":"Testimonial","sub_heading":"What People Say | About Us"},"es":{"heading":null,"sub_heading":null},"ar":{"heading":null,"sub_heading":null}},"items":{"6601421325487":{"language":{"en":{"comment":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"comment":null},"ar":{"comment":null}},"id":"6601421325487","image":"seeder/testi1.webp","name":"Annette Black","designation":"Founder & CEO"},"66014834a16e6":{"language":{"en":{"comment":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"comment":null},"ar":{"comment":null}},"id":"66014834a16e6","image":"seeder/testi2.webp","name":"Groveri","designation":"Software Engineer"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 09:19:08','updated_at' => '2024-03-27 10:48:36'),
            array('key' => 'security-section','value' => '{"language":{"en":{"title":"Security System","heading":"5 Ways To | Security System"},"es":{"title":null,"heading":null},"ar":{"title":null,"heading":null}},"items":{"66013034120dd":{"language":{"en":{"item_title":"SMS or Email Verification","item_heading":"Dramatically supply transparent backward deliverables before caward comp internal or \\"organic\\" sources."},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"status":1,"id":"66013034120dd","icon":"las la-envelope-open-text"},"660130c1a07d2":{"language":{"en":{"item_title":"KYC Solution","item_heading":"Dramatically supply transparent backward deliverables before caward comp internal or \\"organic\\" sources."},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"status":1,"id":"660130c1a07d2","icon":"fas fa-user-check"},"660131c3d2c47":{"language":{"en":{"item_title":"Two Factor Authentication","item_heading":"Dramatically supply transparent backward deliverables before caward comp internal or \\"organic\\" sources."},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"status":1,"id":"660131c3d2c47","icon":"fas fa-qrcode"},"660131edf3ebe":{"language":{"en":{"item_title":"End-to-End Encryption","item_heading":"Dramatically supply transparent backward deliverables before caward comp internal or \\"organic\\" sources."},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"status":1,"id":"660131edf3ebe","icon":"fas fa-compress"},"6601320ac3e20":{"language":{"en":{"item_title":"Behavior Tracking","item_heading":"Dramatically supply transparent backward deliverables before caward comp internal or \\"organic\\" sources."},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"status":1,"id":"6601320ac3e20","icon":"fab fa-bandcamp"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 06:16:47','updated_at' => '2024-03-25 08:22:24'),
            array('key' => 'footer-section','value' => '{"social_links":[{"icon":"fab fa-facebook","link":"https:\\/\\/www.facebook.com\\/appdevsx"},{"icon":"fab fa-instagram","link":"https:\\/\\/www.instagram.com\\/appdevsx"},{"icon":"fab fa-twitter","link":"https:\\/\\/www.twitter.com\\/appdevsx"},{"icon":"fab fa-github","link":"https:\\/\\/www.github.com\\/appdevsx"},{"icon":"fab fa-dribbble","link":"https:\\/\\/www.dribbble.com\\/appdevsx"}],"footer":{"image":""}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 06:53:40','updated_at' => '2024-03-27 03:37:57'),
            array('key' => 'how-its-work-section','value' => '{"image":"seeder/how-work.webp","language":{"en":{"title":"How It Works","heading":"Complete Process for your | NFC Payment"},"es":{"title":null,"heading":null},"ar":{"title":null,"heading":null}},"items":{"660135e62d96e":{"language":{"en":{"item_title":"Registration","item_heading":"Optional service in addition to the purchase of NFC Stickers and NFC Cards"},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"id":"660135e62d96e"},"6601363068985":{"language":{"en":{"item_title":"Add Card","item_heading":"Optional service in addition to the purchase of NFC Stickers and NFC Cards"},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"id":"6601363068985"},"6601363edbd4d":{"language":{"en":{"item_title":"Make Payment","item_heading":"Optional service in addition to the purchase of NFC Stickers and NFC Cards"},"es":{"item_title":null,"item_heading":null},"ar":{"item_title":null,"item_heading":null}},"id":"6601363edbd4d"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 08:26:20','updated_at' => '2024-03-25 08:30:54'),
            array('key' => 'statistic-section','value' => '{"image":"seeder/statistics.webp","language":{"en":{"title":"Overview","heading":"Last 15 years NFC Payment | Statistics","sub_heading":"We trust this NFCPay layout is helpful for your work. You can involve this layout for any reason. You might contribute a little sum by means of PayPal to help TemplateMo in making new layouts consistently."},"es":{"title":null,"heading":null,"sub_heading":null},"ar":{"title":null,"heading":null,"sub_heading":null}},"items":{"66013d745efcf":{"language":{"en":{"title":"Payment Gateway"},"es":{"title":null},"ar":{"title":null}},"id":"66013d745efcf","status":1,"counter_value":"10"},"66013dc2cc5a4":{"language":{"en":{"title":"Currencies"},"es":{"title":null},"ar":{"title":null}},"id":"66013dc2cc5a4","status":1,"counter_value":"100"},"66013df585dfa":{"language":{"en":{"title":"Transactions Per Day"},"es":{"title":null},"ar":{"title":null}},"id":"66013df585dfa","status":1,"counter_value":"500"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 09:01:23','updated_at' => '2024-03-25 09:03:49'),
            array('key' => 'testimonial-section','value' => '{"language":{"en":{"heading":"Testimonial","sub_heading":"What People Say | About Us"},"es":{"heading":null,"sub_heading":null},"ar":{"heading":null,"sub_heading":null}},"items":{"6601421325487":{"language":{"en":{"comment":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"comment":null},"ar":{"comment":null}},"id":"6601421325487","image":"","name":"Annette Black","designation":"Founder & CEO"},"66014834a16e6":{"language":{"en":{"comment":"sdasd"},"es":{"comment":null},"ar":{"comment":null}},"id":"66014834a16e6","image":"","name":"Bangladeshi taka","designation":"asd"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-25 09:19:08','updated_at' => '2024-03-25 09:47:32'),
            array('key' => 'faq-section','value' => '{"language":{"en":{"title":"FAQs","heading":"Frequently Asked | Questions"},"es":{"title":null,"heading":null},"ar":{"title":null,"heading":null}},"items":{"6603a7589e03b":{"language":{"en":{"question":"What is multi-currency account & how does it work?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null},"ar":{"question":null,"answer":null}},"status":1,"id":"6603a7589e03b"},"6603a7a1ecbf6":{"language":{"en":{"question":"What is the best features & services we deliver?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null},"ar":{"question":null,"answer":null}},"status":1,"id":"6603a7a1ecbf6"},"6603a7beaa030":{"language":{"en":{"question":"What Modes Of Payment Do You Accept?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null},"ar":{"question":null,"answer":null}},"status":1,"id":"6603a7beaa030"},"6603a7db15e22":{"language":{"en":{"question":"What happened to the borderless account?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null},"ar":{"question":null,"answer":null}},"status":1,"id":"6603a7db15e22"},"6603a7face8a8":{"language":{"en":{"question":"What is multi-currency account & how does it work?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null},"ar":{"question":null,"answer":null}},"status":1,"id":"6603a7face8a8"},"6603a818b2cf9":{"language":{"en":{"question":"What is the best features & services we deliver?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null},"ar":{"question":null,"answer":null}},"status":1,"id":"6603a818b2cf9"},"6603a8300ad86":{"language":{"en":{"question":"What Modes Of Payment Do You Accept?","answer":"Moreover general optional service in addition to the purchase of NFC Tags. We read all the Unique IDs (UID) of the Tags and send you via email."},"es":{"question":null,"answer":null},"ar":{"question":null,"answer":null}},"status":1,"id":"6603a8300ad86"}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-27 04:57:23','updated_at' => '2024-03-27 05:01:36'),
            array('key' => 'contact-us-section','value' => '{"image":"seeder/contact.webp","language":{"en":{"title":"Contact Us","heading":"Feel free to get in touch | with us"},"es":{"title":null,"heading":null},"ar":{"title":null,"heading":null}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-27 05:55:25','updated_at' => '2024-03-27 05:55:25'),
            array('key' => 'download-app','value' => '{"items":{"6603bd6a32f77":{"language":{"en":{"item_title":"Get it on","item_header":"Google Pay"},"es":{"item_title":null,"item_header":null},"ar":{"item_title":null,"item_header":null}},"id":"6603bd6a32f77","image":"seeder/google-play.webp","icon_image":"seeder/qr-icon.webp","link":"https:\\/\\/play.google.com\\/store\\/games?hl=en&gl=US","created_at":"2024-03-27T06:32:10.223450Z"},"6603be04dd3c8":{"language":{"en":{"item_title":"Download On The","item_header":"Apple Store"},"es":{"item_title":null,"item_header":null},"ar":{"item_title":null,"item_header":null}},"id":"6603be04dd3c8","image":"seeder/apple-store.webp","icon_image":"seeder/qr-icon.webp","link":"https:\\/\\/www.apple.com\\/app-store\\/","created_at":"2024-03-27T06:34:44.912375Z"}},"image":"seeder/download-app.webp","language":{"en":{"title":"Download App","heading":"Download and Register From | Mobile App","sub_heading":"Work with the pro, talented people at the most affordable price to get the most out of your time and cost using mobile apps.\\r\\n\\r\\nIn our dolore with people who are important to you, conversations that bring you to closer to each other and those who enjoy our dishes. Quisque pretium dolor turpis, quis blandit turpis semper ut. Nam malesuada eros nec luctus laoreet. Fusce sodales consequat velit eget dictum. Integer ornare magna."},"es":{"title":null,"heading":null,"sub_heading":null},"ar":{"title":null,"heading":null,"sub_heading":null}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-27 06:32:10','updated_at' => '2024-03-27 07:02:29'),
            array('key' => 'announcement-section','value' => '{"language":{"en":{"title":"Web Journal","heading":"Read Our Recent | Web Journal"},"es":{"title":null,"heading":null},"ar":{"title":null,"heading":null}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-27 07:17:07','updated_at' => '2024-03-27 07:25:48'),
            array('key' => 'login-section','value' => '{"image":"seeder/login.webp","language":{"en":{"title":"Login Information","heading":"Please input your email and login to your account to get access to your dashboard."},"es":{"title":null,"heading":null},"ar":{"title":"Login Information","heading":"Please input your email and login to your account to get access to your dashboard."}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-27 11:01:49','updated_at' => '2024-03-27 11:01:49'),
            array('key' => 'register-section','value' => '{"image":"seeder/register.webp","language":{"en":{"title":"Register Information","heading":"Please input your details and register to your account to get access to your dashboard."},"es":{"title":null,"heading":null},"ar":{"title":"Register Information","heading":"Please input your details and register to your account to get access to your dashboard."}}}','status' => '1','serialize' => NULL,'created_at' => '2024-03-27 11:02:46','updated_at' => '2024-03-27 11:02:46')
        );
        SiteSections::insert($site_sections,['key'],['value','status']);
    }
}
